### ISSUE TITLE
connection stale

### ISSUE THREAD

**Issue by bhaskaraa2** [bitly/pynsq#104]
When Message Handler deals with external resources like download content through HTTP Protocol then it may delay to complete in default timeout duration (30s) and I include the following logic

```python
message.touch()
```

to notify the server that processing of message will be delayed; 
I think pynsq client is closing connection forcibly with assumption of connection as stale due to `conn.last_recv_timestamp` is out date.

pynsq client raises following error 

```bash
2014-11-23 09:24:15,300 nsq.client  : WARNING  [Bhaskar.local:4150:request:process] connection is stale (135.87s), closing
2014-11-23 09:24:15,300 nsq.async   : ERROR    uncaught exception in data event
Traceback (most recent call last):
  File "/Users/bhaskar/ws/DEV/lib/python2.7/site-packages/nsq/async.py", line 207, in _read_body
    self.trigger('data', conn=self, data=data)
  File "/Users/bhaskar/ws/DEV/lib/python2.7/site-packages/nsq/evented_mixin.py", line 59, in trigger
```

**Comment by mreiferson** [comment]
closing, if you can provide example code please re-open

**Comment by bhaskaraa2** [comment]
I am sorry for delay to provide feedback; My Business case requires more than 2-3 mins processing time for each message.  I went through source code nsqd golang code and py client source and I realized that `max_heartbeat_interval` value is not suffcient for my bussines case; I changed `max_heartbeat_interval`  `msg_timeout` `max_req_timeout` for nsqd configuration.

And Specified `heartbeat_interval` in nsq.reader
```py
nsq.Reader(message_handler=request_handler,
                   lookupd_http_addresses=nsq_url,
                   topic='mytopic', channel='process',
                   lookupd_poll_interval=2,
                   heartbeat_interval=heart_beat,
                   max_tries=2)
```
With these configuration changes this issue is not raised.Thanks for your input and support to resolve this issue.

**Comment by mreiferson** [comment]
If you perform long-lived processing on messages you need to avoid blocking the IOLoop rather than adjusting timeouts to account for the time (perform the work asynchronously or use threads).

Your solution definitely works, but those knobs weren't intended to address this problem.

**Comment by bhaskaraa2** [comment]
Thanks mreiferson for your recommendations; I will consider your suggestion in upcoming solution releases
